"""empty message

Revision ID: 8922a251193a
Revises: 8c40413e28ce
Create Date: 2021-06-17 14:51:46.673434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8922a251193a'
down_revision = '8c40413e28ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_code', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
